### ISSUE TITLE
As A User I want to apply a tag color to a Canvas Card

### ISSUE THREAD

**Issue by AnnaSasDev** [code-of-chaos/obsidian-colored_tags_wrangler#61]
## General Info
In the `0.19.x` version of the plugin users were able to set enable a setting to apply tag colors to canvas cards.
It had a general "allow all" button, and a change general opacity

---
### Functional Requirements
- [x] On `data.json` migrate these allow all & opacity settings are applied to the new system
- [x] A new extension is added to the settings page: "Canvas Cards"
    - [x] extension is able to be selected in the dropdown menu
    - [x] Canvas Cards relies on the `Core` features, so they have to exist together
    - [x] Toggle switch to enable background color for the card
    - [x] Toggle switch to enable border color for the card
    - [x] Number input field to set priority over which tag colors the cards, in event of more than one tag in a card

### Technical Requirements
- [x] New extension : "Canvas Cards"
    - [x] CSSWrangler  
    - [x] BaseExtention class
    - [x] IRecord interface

---
## Tasks
- [x] (end of development ) Code Review
